### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by waisan** [yii2mod/yii2-cms#18]
HI, I encountered this error during installation

[Composer\Downloader\TransportException]
  The "http://packagist.org/p/symfony/css-selector%241b5436fed58a3603c50862294d8cf1993c8614049133898e5a4407658cc0816d
  .json" file could not be downloaded (HTTP/1.1 302 Found)

I'm using yii2 advanced package.
Thank you.

**Comment by ihorchepurnyi** [comment]
Hi, maybe it's some problems with packagist.

**Comment by waisan** [comment]
Thanks for reply. Is there any suggestions or alternative way to install this extension?

**Comment by ihorchepurnyi** [comment]
You can try the following steps
* Update your php version to 7.1
* Update composer via command `composer self-update`
* Update composer global packages via command `composer global update`

And after this steps, you can try to install this package again. Maybe, this error occurs because you have old packages or your composer version is old.
